<a href="https://colab.research.google.com/github/mostafizur1997/Deep-Learning/blob/main/00_Tensorflow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import tensorflow
import tensorflow as tf
print(tf.__version__) #check version

2.9.2


In [2]:
#Creating tensor with tf.constant()
#create a scalar(rank with 0)
scalar = tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [4]:
vector = tf.constant([3,4])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

In [5]:
#check dimension
vector.ndim

1

In [6]:
# create a matrix
matrix = tf.constant([[1,2,3],
                      [3,4,5]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
#create tensor
another_matrix= tf.constant([[10.,7.],[3.,4.]], dtype=tf.float32) # specify the datatype
another_matrix


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  4.]], dtype=float32)>

In [9]:
another_matrix.ndim

2

In [10]:
#Even through another matrix contains more numbers, its dimension stay the same
another_matrix.ndim

2

In [11]:
#How about a tensor?3,2,3
tensor =tf.constant([[[1,2,3],[4,5,6]],
                     [[7,8,9],[10,11,12]],
                     [[13,14,15],[16,17,18]]
                     ])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

# scalar: a single number
# vector: a number with direction
# matrix: 2-dimentional array of numbers
# tensor: n-dimensional array of numbers

In [12]:
#Creating tensors with tf.Variable()

changeable_tensor = tf.Variable([10,7])
unchangeable_tensor =tf.constant([10,7])

In [13]:
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
#doesnot support in this way
changeable_tensor[0] =7

TypeError: ignored

In [ ]:
#support the way
changeable_tensor[0].assign(7)

In [ ]:
#assign method is not approprite for constant
unchangeable_tensor[0].assign(7)

In [ ]:
# Create two random ( but the same ) tensors
random_1 = tf.random.Generator.from_seed(42) #set the seed for reproducibility
random_1 = random_1.normal(shape=(3,2)) # create tensor from a normal distribution
random_2 = tf.random.Generator.from_seed(42)
random_2= random_2.normal(shape=(3,2))
random_1 == random_2

random_1, random_2, random_1 == random_2 

In [ ]:
# create two random (and different) tensors
random_3 = tf.random.Generator.from_seed(42)
random_3 =random_3.normal(shape=(3,2))
random_4 = tf.random.Generator. from_seed(11)
random_4 = random_4.normal(shape=(3,2))

In [ ]:
#seed are different so they are not equal
random_3 == random_4

In [ ]:
#shuffle a tensor (valuabel for when you shauffle your data)
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])

#get different results each time
tf.random.shuffle(not_shuffled)

In [ ]:
#shuffle in the same every time using the seed parameter (won't actually the same output)
tf.random.shuffle(not_shuffled)

In [ ]:
tf.random.shuffle(not_shuffled, seed = 42)

In [ ]:
#global seed
tf.random.set_seed(42)

#operation random seed 
tf.random.shuffle(not_shuffled, 42)

#Other ways to make tensor

In [ ]:
#Make a tensor to all ones
tf.ones(shape=(3,2))

In [15]:
#make a tensor of all zeros
tf.zeros(shape=(3,2)) 

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [16]:
#Note:: Matrix is presented by a capital letter (A or X) and Vector is presented by a vector(y or b)

import numpy as np
numpy_A =np.arange(1,25,dtype =np.int32)
A = tf.constant(numpy_A, shape =[2,4,3]) # note the shape total (2*4*3) has to match  the number of elements in the array
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

##Getting information from tensors (shape, rank, size)
* Shape: The length (number of elements) of each of the dimensions of a tensor.
* Rank: The number of tensor dimensions. A scalar has rank 0, a vector has 1, a matricx has rank 2, a tensor has rank n.
* Axis or dimension: a particular dimension of a tensor.
* Size: The total number of items in the tensor

In [17]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor =tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [18]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [19]:
# Get various attribute of tensor

print("Dtype  of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along axis 0 of tensor: ", rank_4_tensor.shape[0])
print("Elements along last axis of tensor: ", rank_4_tensor[-1])
print("Total number of elements (2*3*4): ", tf.size(rank_4_tensor).numpy())

Dtype  of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor:  (2, 3, 4, 5)
Elements along axis 0 of tensor:  2
Elements along last axis of tensor:  tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32)
Total number of elements (2*3*4):  120


In [20]:
#get the first 2 items of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [21]:
#Get the dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [22]:
#Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10,7],[3,4]])


In [23]:
#Get the last item of each row
rank_2_tensor = tf.constant([[10,7],[3,4]])
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [24]:
#Add an extra dimension(to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis] #in Python "..." means "all dimensions prior to"
rank_2_tensor, rank_3_tensor #shape (2,2), shape(2,2,1)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [25]:
tf.expand_dims (rank_2_tensor, axis=-1) #"-1" means last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

#Manipulating tensors (tensor operations)
#Basic Operations 

In [26]:
# add values to a tensor 
addtensor= tf.constant([[10,2],[20,12]])
addtensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 12],
       [30, 22]], dtype=int32)>

In [27]:
#subtract tensor
subtracttensor =  addtensor - 3
subtracttensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, -1],
       [17,  9]], dtype=int32)>

In [28]:
# Multiplication by using * 
Multiplication = subtracttensor *12
Multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 84, -12],
       [204, 108]], dtype=int32)>

In [29]:
#use multiply for multiplication
tf.multiply(addtensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  20],
       [200, 120]], dtype=int32)>

## Matrix Multiplication

In [30]:
# matrix multiplication in tensorflow
print (addtensor)
tf.matmul(addtensor, addtensor)

tf.Tensor(
[[10  2]
 [20 12]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[140,  44],
       [440, 184]], dtype=int32)>

In [31]:
#Matrix multiplication with python operator '@'
addtensor @ addtensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[140,  44],
       [440, 184]], dtype=int32)>

In [32]:
#Create (3,2) tensor
X= tf.constant ([[1,2],[3,4],[5,6]])

#another (3,2) tensor
Y = tf.constant([[7,8],[8,9],[10,11]])

X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 8,  9],
        [10, 11]], dtype=int32)>)

In [33]:
#Try to matrix multiply them (will error)
X @ Y 

InvalidArgumentError: ignored

#We can do this with either
* tf.reshape() - allow us to reshape a tensor into a defined shape
* tf.transpose() - switches the dimensions of a given tensor

In [34]:
# Example of reshape (3,2) --> (2,3)

tf.reshape (Y, shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  8],
       [ 9, 10, 11]], dtype=int32)>

In [35]:
#try matrix multiplication with reshaped Y
X @ tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 25,  28,  30],
       [ 57,  64,  68],
       [ 89, 100, 106]], dtype=int32)>

In [36]:
# Example of transpose (3,2) -> (2,3)
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [37]:
#Try matrix multiplication
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 81,  90],
       [106, 118]], dtype=int32)>

In [38]:
#You can achieve the same result with parameters
tf.matmul(a=X, b=Y, transpose_a =True, transpose_b =False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 81,  90],
       [106, 118]], dtype=int32)>

* (3, 2) @ (2, 3) -> (3, 3) done with X @ tf.reshape(Y, shape=(2, 3))
* (2, 3) @ (3, 2) -> (2, 2) done with tf.matmul(tf.transpose(X), Y)

#The dot product

In [39]:
#tf.matmul() operating using tf.tensordot().
tf.tensordot(tf.transpose(X), Y, axes=1)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 81,  90],
       [106, 118]], dtype=int32)>

In [40]:
print(X)
print(Y)
#perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 7  8]
 [ 8  9]
 [10 11]], shape=(3, 2), dtype=int32)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  26,  32],
       [ 53,  60,  74],
       [ 83,  94, 116]], dtype=int32)>

In [41]:
#matmul by reshaping 
tf.matmul(X, tf.reshape(Y, (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 25,  28,  30],
       [ 57,  64,  68],
       [ 89, 100, 106]], dtype=int32)>

In [42]:
# check the shape 
Y.shape, tf.reshape(Y,(2,3)).shape, tf.transpose(Y).shape

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

In [43]:
# Check values of Y, reshape Y and transpose Y
print("Normal Y:")
print(Y,"/n") # "\" for newline

print("Y reshaped to (2,3)")
print(tf.reshape(Y, (2,3)),"/n")

print("Y transpose value")
print (tf.transpose(Y))



Normal Y:
tf.Tensor(
[[ 7  8]
 [ 8  9]
 [10 11]], shape=(3, 2), dtype=int32) /n
Y reshaped to (2,3)
tf.Tensor(
[[ 7  8  8]
 [ 9 10 11]], shape=(2, 3), dtype=int32) /n
Y transpose value
tf.Tensor(
[[ 7  8 10]
 [ 8  9 11]], shape=(2, 3), dtype=int32)


As you can see, the outputs of tf.reshape() and tf.transpose() when called on Y, even though they have the same shape, are different.

This can be explained by the default behaviour of each method:

tf.reshape() - change the shape of the given tensor (first) and then insert values in order they appear (in our case, 7, 8, 9, 10, 11, 12).
tf.transpose() - swap the order of the axes, by default the last axis becomes the first, however the order can be changed using the perm parameter.

##Matrix multiplication tidbits

##Changing the datatype of a tensor
you can change the datatype of a tensor using 
tf.cast

In [44]:
#defult dataype for A and B
A =tf.constant([1.0,2.0,3.,4.,5.])
B= tf.constant([6,7,8,9,10])

In [45]:
A, B

(<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 6,  7,  8,  9, 10], dtype=int32)>)

In [46]:
# change the datatype by using tf.cast
A= tf.cast(A, dtype=tf.float16)
B= tf.cast(B, dtype= tf.float32)
A, B

(<tf.Tensor: shape=(5,), dtype=float16, numpy=array([1., 2., 3., 4., 5.], dtype=float16)>,
 <tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 6.,  7.,  8.,  9., 10.], dtype=float32)>)

## Getting the absolute value
you can use tf.abs()

In [47]:
# create negative tensor
M = tf.constant([-3,4,-5,8])

In [48]:
#get the absolute value
M= tf.abs(M)

In [49]:
#get the value
M

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 4, 5, 8], dtype=int32)>

#Finding the min, max, mean, sum (aggregation)

* tf.reduce_min() -> minimum value of tensor
 
* tf.reduce_max() -> maximum value of tensor

* tf.reduce_mean() -> find the mean of all tensors

* tf.reduce_sum() -> find the sum of all elements

In [50]:
#Create a tensor with 50 random values between 0 and 100
E =tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([26, 49, 52, 78, 38, 92, 34, 31, 69, 58, 35,  2, 62, 88, 84, 16, 95,
       39,  7, 16, 29, 85, 82,  6, 58, 24, 15, 17, 18, 72,  6, 46, 94,  5,
       98, 69, 62, 26, 89, 67, 62,  0, 42, 45, 19, 87, 77, 58,  7, 80])>

In [51]:
#find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [52]:
#find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [53]:
#find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [54]:
#find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2416>

In [55]:
#find the stadard devition 
tf.reduce_std(E)

AttributeError: ignored

In [ ]:
tf.reduce.variance(E)

## Finding the positional maximum and minimum

* tf.argmax() - find the position of the maximum element in a given tensor.
* tf.argmin() - find the position of the minimum element in a given tensor.

In [ ]:
#create a tensor with 50 values between 0 and 1
F= tf.constant(np.random.random(50))
F

In [ ]:
#find the maximum element position of F
tf.argmax(F)

In [ ]:
# find the minimum element position of F
tf.argmin(F)

## Squeezing a tensor (removing all single dimensions)
Remove single dimensions from a tensor(dimensions with size 1) , you can use tf.squeeze()

In [ ]:
# Create a rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100
G = tf.constant(np.random.randint(0,100,50), shape=(1,1,1,1,50))

In [ ]:
#Squeeze tensor G (remove all 1 dimensions)
G_squeezed =tf.squeeze(G)

In [ ]:
G_squeezed.shape, G_squeezed.ndim

## One-hot encoding
you can use tf.one_hot()

In [ ]:
#Create a list of indicies
some_list =[0,1,2,3]

#One hot encode them
tf.one_hot(some_list, depth=4)

In [ ]:
#Specifiy custom value for on and off instead of the default 0 and 1
tf.one_hot(some_list, depth =4, on_value ="we are live!", off_value="offline")

##Squaring, log, square root

tf.square() - get the square of every value in a tensor.

tf.sqrt() - get the squareroot of every value in a tensor (note: the elements need to be floats or this will error).

tf.math.log() - get the natural log of every value in a tensor (elements need to floats).

In [ ]:
#Create a tensor 
H = tf.constant(np.arange(1,10))
H

In [ ]:
#Square it
tf.square(H)

In [ ]:
#Find the squareroot (will error), needs to be non-integer
tf.sqrt(H)

In [ ]:
#Change H to float2
H = tf.cast(H, dtype= tf.float32)

In [ ]:
H

In [ ]:
#find the squareroot
tf.sqrt(H)

In [ ]:
#Find the log (input also needs to be float)
tf.math.log(H)

## Manipulating tf.variable tensors
.assign() - assign a different value to a particular index of a variable tensor.

.add_assign() - add to an existing value and reassign it at a particular index of a variable tensor.

In [ ]:
#Create a variable tensor
I = tf.Variable(np.arange(0,5))
I

In [ ]:
I.assign([0, 1, 2, 3, 50])

In [ ]:
# the change happen in place (the last value is now 50, not 4)
I

In [ ]:
# Add 10 to every element in I
I.assign_add([10,10,10,10,10])

In [ ]:
#again the changes happens in palce
I

#Tensors and NumPy

np.array() - pass a tensor to convert to an ndarray (NumPy's main datatype).

tensor.numpy() - call on a tensor to convert to an ndarray.

In [ ]:
#create a tensor from a numpy array
J = tf.constant(np.array([3.,5.,7.]))
J

In [ ]:
#covert tensor J to Numpy with np.array()
np.array(J), type(np.array(J))

In [ ]:
#convert tensor J to numpy with .Numpy()
J.numpy(), type(J.numpy())

In [ ]:

# Create a tensor from NumPy and from an array
numpy_J = tf.constant(np.array([3., 7., 10.])) # will be float64 (due to NumPy)
tensor_J = tf.constant([3., 7., 10.]) # will be float32 (due to being TensorFlow default)
numpy_J.dtype, tensor_J.dtype

## Using @tf.function

In [56]:
#Create a simple function, it decorate with @tf.function
#create a simple function
def function(x,y):
  return x**2 + y

x = tf.constant(np.arange(0,10))
y = tf.constant(np.arange(10,20))
function(x,y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [57]:
#create the same function and decorate it with tf.function
@tf.function
def tf_function(x,y):
  return x**2 + y

tf_function(x,y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

## Finding access to GPUs

In [58]:
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [59]:
#you have to change your runtime type
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [60]:
!nvidia-smi

Sat Feb  4 17:49:50 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P0    27W /  70W |    312MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------